name: Docker Swagger Codegen CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Swagger Docker image
      run: docker build . --file Dockerfile --tag swagger-dodegen-cli:$(date +%s)
